### PR TITLE
updated emails to gapsummit.com

### PR DESCRIPTION
**Pull request by lisaar**
update lkaa2.cam.ac.uk to lisa.altmann-richer@gapsummit.com

### CODE REVIEW

**Comment by lisaar** [comment]
would be good to get these merged so we can publicise the trailer. hope youre having a good holiday

**Comment by croydondias** [comment]
Hi Lisa,

I've merged the changes and added the youtube video (you'll have to
uncomment it).

Note, you can't just copy and paste the entire youtube link from your
browser:

src="//www.youtube.com/embed/-IcGvBE5xfg?showinfo=0&rel=0"
You only have to change the highlighted part in the html file.

Cheers,
Croydon

**Comment by lisaar** [comment]
Thanks very much Croydon,

They don’t seem to have gone live yet, but hopefully it’ll update to the live site tonight?

Once that’s done i’ll publish the YouTube video so thanks for setting up a template on the site 

Best,

Lisa

On 5 May 2015 at 22:37:08, Croydon Dias (notifications@github.com) wrote:

Hi Lisa,

I've merged the changes and added the youtube video (you'll have to
uncomment it).

Note, you can't just copy and paste the entire youtube link from your
browser:

src="//www.youtube.com/embed/-IcGvBE5xfg?showinfo=0&rel=0"
You only have to change the highlighted part in the html file.

Cheers,
Croydon

**Comment by croydondias** [comment]
Sorry about that, I missed a step. The latest copy is shown on gapsummit.com
now. :)

**Comment by lisaar** [comment]
thanks very much. 

i may spot a couple of other changes that need making and do the updates tonight, but I’m sure you’ll get a pull request

Thanks for doing all this on your holiday. Enjoy the break!

best,

lisa
-- 
Lisa Altmann-Richer
Sent with Airmail

On 6 May 2015 at 09:22:26, Croydon Dias (notifications@github.com) wrote:

Sorry about that, I missed a step. The latest copy is shown on gapsummit.com
now. :)

**Pull request merged**
